root_user_email    = "example@openobserve.ai"
root_user_password = "CustomSecurePassword123"
o2_domain          = "example.openobserve.ai"
o2_dex_domain      = "example-auth.openobserve.ai"
secret_name        = "example"